### PR TITLE
Prepare to release 0.9.15

### PR DESCRIPTION
**Pull request by gaborigloi**
Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

### CODE REVIEW

**Comment by gaborigloi** [comment]
For some reason we kept incrementing the bugfix version number, but [semver says](http://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase) we should increment the minor. So should I increment the minor version instead, or just follow the pattern (as I did in this PR)?

**Comment by mseri** [comment]
For this package, I think we should follow the pattern

**Comment by gaborigloi** [comment]
Should we also update this in the main opam repo?

**Comment by mseri** [comment]
Would this have issues if used with the released xapi version?

**Comment by gaborigloi** [comment]
@mseri Probably not with a xapi version in a current XS release.

**Comment by gaborigloi** [comment]
PR for xs-opam: https://github.com/xapi-project/xs-opam/pull/115

**Comment by mseri** [comment]
Thanks, so let's only release it on xs-opam for now

**Pull request merged**
