### PR TITLE
Remove camlp4 and update api

### PR DESCRIPTION
**Pull request by gaborigloi**
Switch from camlp4 rpc syntax to the ppx one, and from the camlp4 lwt syntax to the plain one.

Also, ocp-indent the whole codebase.

Probably I should squash the commits before merging.

### CODE REVIEW

**Comment by mseri** [comment]
Can you run ocp-indent on th whole codebase?
Also some functions in Lwt.catch and Lwt.finalize are massive, it might be more readable if we exctract them. I will have a better look on Monday

**Comment by gaborigloi** [comment]
@mseri sounds good, I like the idea of ocp-indenting everything :smile: , I'll first send a PR for that.

**Comment by mseri** [comment]
The indented code is much easier to read. As far as I uderstood, most of the files are autogenerated xapi files. Without entering into the details of the code, that is much more readable after re-indentation, it looks that the translation from camlp4_lwt to lwt, and the port to the new rpc is sound.

For what concerns the tests, unfortunately the only other tests that we have did show the same message: https://travis-ci.org/xapi-project/xen-api-client/jobs/214735313 (and that seems to come from the rpc call to xapi using `one_attempt`: https://github.com/xapi-project/xen-api-client/blob/3b8006df840167f67ebee42e525285f1a64e1c3f/lib/xen_api.ml#L155)

**Comment by gaborigloi** [comment]
Maybe these "failed to read response" messages are emitted during the `test_login_fail` test in `lib_test/xen_api_test.ml`.

**Comment by gaborigloi** [comment]
After running the tests with the `-verbose` flag, I can confirm that the "`failed to read response`" messages are printed during the `login_fail`, which passes.

**Pull request merged**
